// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/backup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WhenToBackup     string                 `protobuf:"bytes,1,opt,name=whenToBackup,proto3" json:"whenToBackup,omitempty"`
	WhatToBackup     []string               `protobuf:"bytes,2,rep,name=whatToBackup,proto3" json:"whatToBackup,omitempty"`
	Exclude          []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	IsFullBackupOnly bool                   `protobuf:"varint,4,opt,name=isFullBackupOnly,proto3" json:"isFullBackupOnly,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackupConfig) Reset() {
	*x = BackupConfig{}
	mi := &file_protos_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupConfig) ProtoMessage() {}

func (x *BackupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupConfig.ProtoReflect.Descriptor instead.
func (*BackupConfig) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupConfig) GetWhenToBackup() string {
	if x != nil {
		return x.WhenToBackup
	}
	return ""
}

func (x *BackupConfig) GetWhatToBackup() []string {
	if x != nil {
		return x.WhatToBackup
	}
	return nil
}

func (x *BackupConfig) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *BackupConfig) GetIsFullBackupOnly() bool {
	if x != nil {
		return x.IsFullBackupOnly
	}
	return false
}

type BackupConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupConfigRequest) Reset() {
	*x = BackupConfigRequest{}
	mi := &file_protos_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupConfigRequest) ProtoMessage() {}

func (x *BackupConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupConfigRequest.ProtoReflect.Descriptor instead.
func (*BackupConfigRequest) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{1}
}

type BackupConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupConfig  *BackupConfig          `protobuf:"bytes,1,opt,name=backupConfig,proto3" json:"backupConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupConfigResponse) Reset() {
	*x = BackupConfigResponse{}
	mi := &file_protos_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupConfigResponse) ProtoMessage() {}

func (x *BackupConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupConfigResponse.ProtoReflect.Descriptor instead.
func (*BackupConfigResponse) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupConfigResponse) GetBackupConfig() *BackupConfig {
	if x != nil {
		return x.BackupConfig
	}
	return nil
}

type BackupStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStartRequest) Reset() {
	*x = BackupStartRequest{}
	mi := &file_protos_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStartRequest) ProtoMessage() {}

func (x *BackupStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStartRequest.ProtoReflect.Descriptor instead.
func (*BackupStartRequest) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupStartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupStartRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BackupStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStartResponse) Reset() {
	*x = BackupStartResponse{}
	mi := &file_protos_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStartResponse) ProtoMessage() {}

func (x *BackupStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStartResponse.ProtoReflect.Descriptor instead.
func (*BackupStartResponse) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupStartResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type BackupChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChunkName     string                 `protobuf:"bytes,2,opt,name=chunkName,proto3" json:"chunkName,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunk) Reset() {
	*x = BackupChunk{}
	mi := &file_protos_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunk) ProtoMessage() {}

func (x *BackupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunk.ProtoReflect.Descriptor instead.
func (*BackupChunk) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{5}
}

func (x *BackupChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupChunk) GetChunkName() string {
	if x != nil {
		return x.ChunkName
	}
	return ""
}

func (x *BackupChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BackupChunk) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BackupChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *BackupChunk           `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunkRequest) Reset() {
	*x = BackupChunkRequest{}
	mi := &file_protos_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunkRequest) ProtoMessage() {}

func (x *BackupChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunkRequest.ProtoReflect.Descriptor instead.
func (*BackupChunkRequest) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupChunkRequest) GetChunk() *BackupChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type BackupChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkName     string                 `protobuf:"bytes,1,opt,name=chunkName,proto3" json:"chunkName,omitempty"`
	IsOk          bool                   `protobuf:"varint,2,opt,name=isOk,proto3" json:"isOk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunkResponse) Reset() {
	*x = BackupChunkResponse{}
	mi := &file_protos_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunkResponse) ProtoMessage() {}

func (x *BackupChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunkResponse.ProtoReflect.Descriptor instead.
func (*BackupChunkResponse) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupChunkResponse) GetChunkName() string {
	if x != nil {
		return x.ChunkName
	}
	return ""
}

func (x *BackupChunkResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type BackupEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupEndRequest) Reset() {
	*x = BackupEndRequest{}
	mi := &file_protos_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupEndRequest) ProtoMessage() {}

func (x *BackupEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupEndRequest.ProtoReflect.Descriptor instead.
func (*BackupEndRequest) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{8}
}

func (x *BackupEndRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BackupEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupEndResponse) Reset() {
	*x = BackupEndResponse{}
	mi := &file_protos_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupEndResponse) ProtoMessage() {}

func (x *BackupEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupEndResponse.ProtoReflect.Descriptor instead.
func (*BackupEndResponse) Descriptor() ([]byte, []int) {
	return file_protos_backup_proto_rawDescGZIP(), []int{9}
}

func (x *BackupEndResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

var File_protos_backup_proto protoreflect.FileDescriptor

const file_protos_backup_proto_rawDesc = "" +
	"\n" +
	"\x13protos/backup.proto\x12\arequest\"\x9c\x01\n" +
	"\fBackupConfig\x12\"\n" +
	"\fwhenToBackup\x18\x01 \x01(\tR\fwhenToBackup\x12\"\n" +
	"\fwhatToBackup\x18\x02 \x03(\tR\fwhatToBackup\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12*\n" +
	"\x10isFullBackupOnly\x18\x04 \x01(\bR\x10isFullBackupOnly\"\x15\n" +
	"\x13BackupConfigRequest\"Q\n" +
	"\x14BackupConfigResponse\x129\n" +
	"\fbackupConfig\x18\x01 \x01(\v2\x15.request.BackupConfigR\fbackupConfig\"<\n" +
	"\x12BackupStartRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\")\n" +
	"\x13BackupStartResponse\x12\x12\n" +
	"\x04isOk\x18\x01 \x01(\bR\x04isOk\"g\n" +
	"\vBackupChunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tchunkName\x18\x02 \x01(\tR\tchunkName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"@\n" +
	"\x12BackupChunkRequest\x12*\n" +
	"\x05chunk\x18\x01 \x01(\v2\x14.request.BackupChunkR\x05chunk\"G\n" +
	"\x13BackupChunkResponse\x12\x1c\n" +
	"\tchunkName\x18\x01 \x01(\tR\tchunkName\x12\x12\n" +
	"\x04isOk\x18\x02 \x01(\bR\x04isOk\"&\n" +
	"\x10BackupEndRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11BackupEndResponse\x12\x12\n" +
	"\x04isOk\x18\x01 \x01(\bR\x04isOkB\bZ\x06/protob\x06proto3"

var (
	file_protos_backup_proto_rawDescOnce sync.Once
	file_protos_backup_proto_rawDescData []byte
)

func file_protos_backup_proto_rawDescGZIP() []byte {
	file_protos_backup_proto_rawDescOnce.Do(func() {
		file_protos_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_backup_proto_rawDesc), len(file_protos_backup_proto_rawDesc)))
	})
	return file_protos_backup_proto_rawDescData
}

var file_protos_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_backup_proto_goTypes = []any{
	(*BackupConfig)(nil),         // 0: request.BackupConfig
	(*BackupConfigRequest)(nil),  // 1: request.BackupConfigRequest
	(*BackupConfigResponse)(nil), // 2: request.BackupConfigResponse
	(*BackupStartRequest)(nil),   // 3: request.BackupStartRequest
	(*BackupStartResponse)(nil),  // 4: request.BackupStartResponse
	(*BackupChunk)(nil),          // 5: request.BackupChunk
	(*BackupChunkRequest)(nil),   // 6: request.BackupChunkRequest
	(*BackupChunkResponse)(nil),  // 7: request.BackupChunkResponse
	(*BackupEndRequest)(nil),     // 8: request.BackupEndRequest
	(*BackupEndResponse)(nil),    // 9: request.BackupEndResponse
}
var file_protos_backup_proto_depIdxs = []int32{
	0, // 0: request.BackupConfigResponse.backupConfig:type_name -> request.BackupConfig
	5, // 1: request.BackupChunkRequest.chunk:type_name -> request.BackupChunk
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_backup_proto_init() }
func file_protos_backup_proto_init() {
	if File_protos_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_backup_proto_rawDesc), len(file_protos_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_backup_proto_goTypes,
		DependencyIndexes: file_protos_backup_proto_depIdxs,
		MessageInfos:      file_protos_backup_proto_msgTypes,
	}.Build()
	File_protos_backup_proto = out.File
	file_protos_backup_proto_goTypes = nil
	file_protos_backup_proto_depIdxs = nil
}
