// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_protos_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_protos_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Client) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Client) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

var File_protos_client_proto protoreflect.FileDescriptor

const file_protos_client_proto_rawDesc = "" +
	"\n" +
	"\x13protos/client.proto\x12\x06client\"V\n" +
	"\x06Client\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpointB\bZ\x06/protob\x06proto3"

var (
	file_protos_client_proto_rawDescOnce sync.Once
	file_protos_client_proto_rawDescData []byte
)

func file_protos_client_proto_rawDescGZIP() []byte {
	file_protos_client_proto_rawDescOnce.Do(func() {
		file_protos_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_client_proto_rawDesc), len(file_protos_client_proto_rawDesc)))
	})
	return file_protos_client_proto_rawDescData
}

var file_protos_client_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_client_proto_goTypes = []any{
	(*Client)(nil), // 0: client.Client
}
var file_protos_client_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_client_proto_init() }
func file_protos_client_proto_init() {
	if File_protos_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_client_proto_rawDesc), len(file_protos_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_client_proto_goTypes,
		DependencyIndexes: file_protos_client_proto_depIdxs,
		MessageInfos:      file_protos_client_proto_msgTypes,
	}.Build()
	File_protos_client_proto = out.File
	file_protos_client_proto_goTypes = nil
	file_protos_client_proto_depIdxs = nil
}
