// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/envelope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_BackupConfigRequest
	//	*Envelope_BackupConfigResponse
	//	*Envelope_BackupChunkRequest
	//	*Envelope_BackupChunkResponse
	//	*Envelope_BackupStartRequest
	//	*Envelope_BackupStartResponse
	//	*Envelope_BackupEndRequest
	//	*Envelope_BackupEndResponse
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protos_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetBackupConfigRequest() *BackupConfigRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupConfigRequest); ok {
			return x.BackupConfigRequest
		}
	}
	return nil
}

func (x *Envelope) GetBackupConfigResponse() *BackupConfigResponse {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupConfigResponse); ok {
			return x.BackupConfigResponse
		}
	}
	return nil
}

func (x *Envelope) GetBackupChunkRequest() *BackupChunkRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupChunkRequest); ok {
			return x.BackupChunkRequest
		}
	}
	return nil
}

func (x *Envelope) GetBackupChunkResponse() *BackupChunkResponse {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupChunkResponse); ok {
			return x.BackupChunkResponse
		}
	}
	return nil
}

func (x *Envelope) GetBackupStartRequest() *BackupStartRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupStartRequest); ok {
			return x.BackupStartRequest
		}
	}
	return nil
}

func (x *Envelope) GetBackupStartResponse() *BackupStartResponse {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupStartResponse); ok {
			return x.BackupStartResponse
		}
	}
	return nil
}

func (x *Envelope) GetBackupEndRequest() *BackupEndRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupEndRequest); ok {
			return x.BackupEndRequest
		}
	}
	return nil
}

func (x *Envelope) GetBackupEndResponse() *BackupEndResponse {
	if x != nil {
		if x, ok := x.Message.(*Envelope_BackupEndResponse); ok {
			return x.BackupEndResponse
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_BackupConfigRequest struct {
	BackupConfigRequest *BackupConfigRequest `protobuf:"bytes,2,opt,name=backupConfigRequest,proto3,oneof"`
}

type Envelope_BackupConfigResponse struct {
	BackupConfigResponse *BackupConfigResponse `protobuf:"bytes,3,opt,name=backupConfigResponse,proto3,oneof"`
}

type Envelope_BackupChunkRequest struct {
	BackupChunkRequest *BackupChunkRequest `protobuf:"bytes,4,opt,name=backupChunkRequest,proto3,oneof"`
}

type Envelope_BackupChunkResponse struct {
	BackupChunkResponse *BackupChunkResponse `protobuf:"bytes,5,opt,name=backupChunkResponse,proto3,oneof"`
}

type Envelope_BackupStartRequest struct {
	BackupStartRequest *BackupStartRequest `protobuf:"bytes,6,opt,name=backupStartRequest,proto3,oneof"`
}

type Envelope_BackupStartResponse struct {
	BackupStartResponse *BackupStartResponse `protobuf:"bytes,7,opt,name=backupStartResponse,proto3,oneof"`
}

type Envelope_BackupEndRequest struct {
	BackupEndRequest *BackupEndRequest `protobuf:"bytes,8,opt,name=backupEndRequest,proto3,oneof"`
}

type Envelope_BackupEndResponse struct {
	BackupEndResponse *BackupEndResponse `protobuf:"bytes,9,opt,name=backupEndResponse,proto3,oneof"`
}

func (*Envelope_BackupConfigRequest) isEnvelope_Message() {}

func (*Envelope_BackupConfigResponse) isEnvelope_Message() {}

func (*Envelope_BackupChunkRequest) isEnvelope_Message() {}

func (*Envelope_BackupChunkResponse) isEnvelope_Message() {}

func (*Envelope_BackupStartRequest) isEnvelope_Message() {}

func (*Envelope_BackupStartResponse) isEnvelope_Message() {}

func (*Envelope_BackupEndRequest) isEnvelope_Message() {}

func (*Envelope_BackupEndResponse) isEnvelope_Message() {}

var File_protos_envelope_proto protoreflect.FileDescriptor

const file_protos_envelope_proto_rawDesc = "" +
	"\n" +
	"\x15protos/envelope.proto\x12\arequest\x1a\x13protos/backup.proto\"\xaf\x05\n" +
	"\bEnvelope\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12P\n" +
	"\x13backupConfigRequest\x18\x02 \x01(\v2\x1c.request.BackupConfigRequestH\x00R\x13backupConfigRequest\x12S\n" +
	"\x14backupConfigResponse\x18\x03 \x01(\v2\x1d.request.BackupConfigResponseH\x00R\x14backupConfigResponse\x12M\n" +
	"\x12backupChunkRequest\x18\x04 \x01(\v2\x1b.request.BackupChunkRequestH\x00R\x12backupChunkRequest\x12P\n" +
	"\x13backupChunkResponse\x18\x05 \x01(\v2\x1c.request.BackupChunkResponseH\x00R\x13backupChunkResponse\x12M\n" +
	"\x12backupStartRequest\x18\x06 \x01(\v2\x1b.request.BackupStartRequestH\x00R\x12backupStartRequest\x12P\n" +
	"\x13backupStartResponse\x18\a \x01(\v2\x1c.request.BackupStartResponseH\x00R\x13backupStartResponse\x12G\n" +
	"\x10backupEndRequest\x18\b \x01(\v2\x19.request.BackupEndRequestH\x00R\x10backupEndRequest\x12J\n" +
	"\x11backupEndResponse\x18\t \x01(\v2\x1a.request.BackupEndResponseH\x00R\x11backupEndResponseB\t\n" +
	"\amessageB\bZ\x06/protob\x06proto3"

var (
	file_protos_envelope_proto_rawDescOnce sync.Once
	file_protos_envelope_proto_rawDescData []byte
)

func file_protos_envelope_proto_rawDescGZIP() []byte {
	file_protos_envelope_proto_rawDescOnce.Do(func() {
		file_protos_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_envelope_proto_rawDesc), len(file_protos_envelope_proto_rawDesc)))
	})
	return file_protos_envelope_proto_rawDescData
}

var file_protos_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_envelope_proto_goTypes = []any{
	(*Envelope)(nil),             // 0: request.Envelope
	(*BackupConfigRequest)(nil),  // 1: request.BackupConfigRequest
	(*BackupConfigResponse)(nil), // 2: request.BackupConfigResponse
	(*BackupChunkRequest)(nil),   // 3: request.BackupChunkRequest
	(*BackupChunkResponse)(nil),  // 4: request.BackupChunkResponse
	(*BackupStartRequest)(nil),   // 5: request.BackupStartRequest
	(*BackupStartResponse)(nil),  // 6: request.BackupStartResponse
	(*BackupEndRequest)(nil),     // 7: request.BackupEndRequest
	(*BackupEndResponse)(nil),    // 8: request.BackupEndResponse
}
var file_protos_envelope_proto_depIdxs = []int32{
	1, // 0: request.Envelope.backupConfigRequest:type_name -> request.BackupConfigRequest
	2, // 1: request.Envelope.backupConfigResponse:type_name -> request.BackupConfigResponse
	3, // 2: request.Envelope.backupChunkRequest:type_name -> request.BackupChunkRequest
	4, // 3: request.Envelope.backupChunkResponse:type_name -> request.BackupChunkResponse
	5, // 4: request.Envelope.backupStartRequest:type_name -> request.BackupStartRequest
	6, // 5: request.Envelope.backupStartResponse:type_name -> request.BackupStartResponse
	7, // 6: request.Envelope.backupEndRequest:type_name -> request.BackupEndRequest
	8, // 7: request.Envelope.backupEndResponse:type_name -> request.BackupEndResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_protos_envelope_proto_init() }
func file_protos_envelope_proto_init() {
	if File_protos_envelope_proto != nil {
		return
	}
	file_protos_backup_proto_init()
	file_protos_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_BackupConfigRequest)(nil),
		(*Envelope_BackupConfigResponse)(nil),
		(*Envelope_BackupChunkRequest)(nil),
		(*Envelope_BackupChunkResponse)(nil),
		(*Envelope_BackupStartRequest)(nil),
		(*Envelope_BackupStartResponse)(nil),
		(*Envelope_BackupEndRequest)(nil),
		(*Envelope_BackupEndResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_envelope_proto_rawDesc), len(file_protos_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_envelope_proto_goTypes,
		DependencyIndexes: file_protos_envelope_proto_depIdxs,
		MessageInfos:      file_protos_envelope_proto_msgTypes,
	}.Build()
	File_protos_envelope_proto = out.File
	file_protos_envelope_proto_goTypes = nil
	file_protos_envelope_proto_depIdxs = nil
}
