// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailReceiver string                 `protobuf:"bytes,1,opt,name=emailReceiver,proto3" json:"emailReceiver,omitempty"`
	EmailSender   string                 `protobuf:"bytes,2,opt,name=emailSender,proto3" json:"emailSender,omitempty"`
	EmailUser     string                 `protobuf:"bytes,3,opt,name=emailUser,proto3" json:"emailUser,omitempty"`
	EmailPassword string                 `protobuf:"bytes,4,opt,name=emailPassword,proto3" json:"emailPassword,omitempty"`
	EmailHost     string                 `protobuf:"bytes,5,opt,name=emailHost,proto3" json:"emailHost,omitempty"`
	EmailPort     int32                  `protobuf:"varint,6,opt,name=emailPort,proto3" json:"emailPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_protos_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_protos_server_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetEmailReceiver() string {
	if x != nil {
		return x.EmailReceiver
	}
	return ""
}

func (x *Email) GetEmailSender() string {
	if x != nil {
		return x.EmailSender
	}
	return ""
}

func (x *Email) GetEmailUser() string {
	if x != nil {
		return x.EmailUser
	}
	return ""
}

func (x *Email) GetEmailPassword() string {
	if x != nil {
		return x.EmailPassword
	}
	return ""
}

func (x *Email) GetEmailHost() string {
	if x != nil {
		return x.EmailHost
	}
	return ""
}

func (x *Email) GetEmailPort() int32 {
	if x != nil {
		return x.EmailPort
	}
	return 0
}

type Discord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DiscordWebHookId    string                 `protobuf:"bytes,1,opt,name=discordWebHookId,proto3" json:"discordWebHookId,omitempty"`
	DiscordWebHookToken string                 `protobuf:"bytes,2,opt,name=discordWebHookToken,proto3" json:"discordWebHookToken,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Discord) Reset() {
	*x = Discord{}
	mi := &file_protos_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discord) ProtoMessage() {}

func (x *Discord) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discord.ProtoReflect.Descriptor instead.
func (*Discord) Descriptor() ([]byte, []int) {
	return file_protos_server_proto_rawDescGZIP(), []int{1}
}

func (x *Discord) GetDiscordWebHookId() string {
	if x != nil {
		return x.DiscordWebHookId
	}
	return ""
}

func (x *Discord) GetDiscordWebHookToken() string {
	if x != nil {
		return x.DiscordWebHookToken
	}
	return ""
}

type Server struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Port                          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Domain                        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Username                      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password                      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	BackupPath                    string                 `protobuf:"bytes,5,opt,name=backupPath,proto3" json:"backupPath,omitempty"`
	StorageAlertTresholdInPercent int32                  `protobuf:"varint,6,opt,name=storageAlertTresholdInPercent,proto3" json:"storageAlertTresholdInPercent,omitempty"`
	RegisterNodeIfNotKnown        bool                   `protobuf:"varint,7,opt,name=registerNodeIfNotKnown,proto3" json:"registerNodeIfNotKnown,omitempty"`
	EmailAlert                    bool                   `protobuf:"varint,8,opt,name=emailAlert,proto3" json:"emailAlert,omitempty"`
	Email                         *Email                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	DiscordAlert                  bool                   `protobuf:"varint,10,opt,name=discordAlert,proto3" json:"discordAlert,omitempty"`
	Discord                       *Discord               `protobuf:"bytes,11,opt,name=discord,proto3" json:"discord,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_protos_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_protos_server_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Server) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Server) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Server) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Server) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *Server) GetStorageAlertTresholdInPercent() int32 {
	if x != nil {
		return x.StorageAlertTresholdInPercent
	}
	return 0
}

func (x *Server) GetRegisterNodeIfNotKnown() bool {
	if x != nil {
		return x.RegisterNodeIfNotKnown
	}
	return false
}

func (x *Server) GetEmailAlert() bool {
	if x != nil {
		return x.EmailAlert
	}
	return false
}

func (x *Server) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *Server) GetDiscordAlert() bool {
	if x != nil {
		return x.DiscordAlert
	}
	return false
}

func (x *Server) GetDiscord() *Discord {
	if x != nil {
		return x.Discord
	}
	return nil
}

var File_protos_server_proto protoreflect.FileDescriptor

const file_protos_server_proto_rawDesc = "" +
	"\n" +
	"\x13protos/server.proto\x12\x06server\"\xcf\x01\n" +
	"\x05Email\x12$\n" +
	"\remailReceiver\x18\x01 \x01(\tR\remailReceiver\x12 \n" +
	"\vemailSender\x18\x02 \x01(\tR\vemailSender\x12\x1c\n" +
	"\temailUser\x18\x03 \x01(\tR\temailUser\x12$\n" +
	"\remailPassword\x18\x04 \x01(\tR\remailPassword\x12\x1c\n" +
	"\temailHost\x18\x05 \x01(\tR\temailHost\x12\x1c\n" +
	"\temailPort\x18\x06 \x01(\x05R\temailPort\"g\n" +
	"\aDiscord\x12*\n" +
	"\x10discordWebHookId\x18\x01 \x01(\tR\x10discordWebHookId\x120\n" +
	"\x13discordWebHookToken\x18\x02 \x01(\tR\x13discordWebHookToken\"\x9e\x03\n" +
	"\x06Server\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"backupPath\x18\x05 \x01(\tR\n" +
	"backupPath\x12D\n" +
	"\x1dstorageAlertTresholdInPercent\x18\x06 \x01(\x05R\x1dstorageAlertTresholdInPercent\x126\n" +
	"\x16registerNodeIfNotKnown\x18\a \x01(\bR\x16registerNodeIfNotKnown\x12\x1e\n" +
	"\n" +
	"emailAlert\x18\b \x01(\bR\n" +
	"emailAlert\x12#\n" +
	"\x05email\x18\f \x01(\v2\r.server.EmailR\x05email\x12\"\n" +
	"\fdiscordAlert\x18\n" +
	" \x01(\bR\fdiscordAlert\x12)\n" +
	"\adiscord\x18\v \x01(\v2\x0f.server.DiscordR\adiscordB\bZ\x06/protob\x06proto3"

var (
	file_protos_server_proto_rawDescOnce sync.Once
	file_protos_server_proto_rawDescData []byte
)

func file_protos_server_proto_rawDescGZIP() []byte {
	file_protos_server_proto_rawDescOnce.Do(func() {
		file_protos_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_server_proto_rawDesc), len(file_protos_server_proto_rawDesc)))
	})
	return file_protos_server_proto_rawDescData
}

var file_protos_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_server_proto_goTypes = []any{
	(*Email)(nil),   // 0: server.Email
	(*Discord)(nil), // 1: server.Discord
	(*Server)(nil),  // 2: server.Server
}
var file_protos_server_proto_depIdxs = []int32{
	0, // 0: server.Server.email:type_name -> server.Email
	1, // 1: server.Server.discord:type_name -> server.Discord
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_server_proto_init() }
func file_protos_server_proto_init() {
	if File_protos_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_server_proto_rawDesc), len(file_protos_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_server_proto_goTypes,
		DependencyIndexes: file_protos_server_proto_depIdxs,
		MessageInfos:      file_protos_server_proto_msgTypes,
	}.Build()
	File_protos_server_proto = out.File
	file_protos_server_proto_goTypes = nil
	file_protos_server_proto_depIdxs = nil
}
